### ISSUE TITLE
App crashes after logging into the game

### ISSUE THREAD

**Issue by shobhitagarwal1612** [Software-Incubator/DirectMe-Android-Client#21]
@shobhitgarg9536 App throws an unhandled exception and gives null pointer exception. Refer to the attached log. I think this bug is introduced after integrating FCM. Look into the logcat and find out the reason of the error.

```
02-19 02:31:07.834 16225-16225/com.silab.direct_me W/System.err: org.json.JSONException: End of input at character 0 of 
02-19 02:31:07.835 16225-16259/com.silab.direct_me W/System.err: java.net.MalformedURLException: Protocol not found: 
02-19 02:31:07.835 16225-16225/com.silab.direct_me W/System.err:     at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
02-19 02:31:07.835 16225-16225/com.silab.direct_me W/System.err:     at org.json.JSONTokener.nextValue(JSONTokener.java:97)
02-19 02:31:07.835 16225-16225/com.silab.direct_me W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:155)
02-19 02:31:07.836 16225-16225/com.silab.direct_me W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:172)
02-19 02:31:07.836 16225-16225/com.silab.direct_me W/System.err:     at com.silab.direct_me.Activity.Dashboard$3.processFinish(Dashboard.java:137)
02-19 02:31:07.836 16225-16225/com.silab.direct_me W/System.err:     at com.silab.direct_me.AsyncTask.ApiCalling.onPostExecute(ApiCalling.java:156)
02-19 02:31:07.836 16225-16225/com.silab.direct_me W/System.err:     at com.silab.direct_me.AsyncTask.ApiCalling.onPostExecute(ApiCalling.java:29)
02-19 02:31:07.837 16225-16225/com.silab.direct_me W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:632)
02-19 02:31:07.837 16225-16225/com.silab.direct_me W/System.err:     at android.os.AsyncTask.access$600(AsyncTask.java:177)
02-19 02:31:07.837 16225-16225/com.silab.direct_me W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
02-19 02:31:07.837 16225-16225/com.silab.direct_me W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
02-19 02:31:07.837 16225-16225/com.silab.direct_me W/System.err:     at android.os.Looper.loop(Looper.java:193)
02-19 02:31:07.838 16225-16225/com.silab.direct_me W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5292)
02-19 02:31:07.838 16225-16225/com.silab.direct_me W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
02-19 02:31:07.838 16225-16225/com.silab.direct_me W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
02-19 02:31:07.838 16225-16225/com.silab.direct_me W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
02-19 02:31:07.838 16225-16225/com.silab.direct_me W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
02-19 02:31:07.839 16225-16225/com.silab.direct_me W/System.err:     at dalvik.system.NativeStart.main(Native Method)
02-19 02:31:07.840 16225-16259/com.silab.direct_me W/System.err:     at java.net.URL.<init>(URL.java:176)
02-19 02:31:07.840 16225-16259/com.silab.direct_me W/System.err:     at java.net.URL.<init>(URL.java:125)
02-19 02:31:07.840 16225-16259/com.silab.direct_me W/System.err:     at com.silab.direct_me.AsyncTask.FirebaseTokenBackgroundWorker.doInBackground(FirebaseTokenBackgroundWorker.java:39)
02-19 02:31:07.840 16225-16259/com.silab.direct_me W/System.err:     at com.silab.direct_me.AsyncTask.FirebaseTokenBackgroundWorker.doInBackground(FirebaseTokenBackgroundWorker.java:21)
02-19 02:31:07.840 16225-16259/com.silab.direct_me W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-19 02:31:07.840 16225-16259/com.silab.direct_me W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-19 02:31:07.840 16225-16259/com.silab.direct_me W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-19 02:31:07.840 16225-16259/com.silab.direct_me W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-19 02:31:07.841 16225-16259/com.silab.direct_me W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-19 02:31:07.841 16225-16259/com.silab.direct_me W/System.err:     at java.lang.Thread.run(Thread.java:841)
02-19 02:31:07.841 16225-16225/com.silab.direct_me D/AndroidRuntime: Shutting down VM
02-19 02:31:07.841 16225-16225/com.silab.direct_me W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41f8dc98)
02-19 02:31:07.841 16225-16225/com.silab.direct_me W/dalvikvm: threadid=1: uncaught exception occurred
02-19 02:31:07.841 16225-16225/com.silab.direct_me W/System.err: java.lang.NullPointerException
02-19 02:31:07.843 16225-16225/com.silab.direct_me W/System.err:     at com.android.internal.os.LoggingPrintStream.println(LoggingPrintStream.java:298)
02-19 02:31:07.843 16225-16225/com.silab.direct_me W/System.err:     at com.silab.direct_me.Activity.Dashboard$1.processFinish(Dashboard.java:95)
02-19 02:31:07.844 16225-16225/com.silab.direct_me W/System.err:     at com.silab.direct_me.AsyncTask.FirebaseTokenBackgroundWorker.onPostExecute(FirebaseTokenBackgroundWorker.java:72)
02-19 02:31:07.844 16225-16225/com.silab.direct_me W/System.err:     at com.silab.direct_me.AsyncTask.FirebaseTokenBackgroundWorker.onPostExecute(FirebaseTokenBackgroundWorker.java:21)
02-19 02:31:07.844 16225-16225/com.silab.direct_me W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:632)
02-19 02:31:07.844 16225-16225/com.silab.direct_me W/System.err:     at android.os.AsyncTask.access$600(AsyncTask.java:177)
02-19 02:31:07.844 16225-16225/com.silab.direct_me W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
02-19 02:31:07.844 16225-16225/com.silab.direct_me W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
02-19 02:31:07.844 16225-16225/com.silab.direct_me W/System.err:     at android.os.Looper.loop(Looper.java:193)
02-19 02:31:07.844 16225-16225/com.silab.direct_me W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5292)
02-19 02:31:07.844 16225-16225/com.silab.direct_me W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
02-19 02:31:07.845 16225-16225/com.silab.direct_me W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
02-19 02:31:07.845 16225-16225/com.silab.direct_me W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
02-19 02:31:07.845 16225-16225/com.silab.direct_me W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
02-19 02:31:07.845 16225-16225/com.silab.direct_me W/System.err:     at dalvik.system.NativeStart.main(Native Method)
02-19 02:31:07.845 16225-16225/com.silab.direct_me W/dalvikvm: threadid=1: calling UncaughtExceptionHandler

```

**Comment by shobhitagarwal1612** [comment]
This bug is resolved by #39
